### ISSUE TITLE
db hint

### ISSUE THREAD

**Issue by vitaly-t** [matthewfranglen/minecraft-bot#1]
you are missing a step here: https://github.com/matthewfranglen/minecraft-bot/blob/master/lib/src/state/database.js
where you pass initialization options into pg-pormise, and only then use the returned instance to create the `db` object from connection details.

Check the [Getting Started](https://github.com/vitaly-t/pg-promise#getting-started) once again ;)

**Comment by matthewfranglen** [comment]
I think I uploaded this to github yesterday approx 10:58pm. You opened this ticket at 12:48am. I am just blown away by how responsive you are to uses of your library.

I have made the changes and tested it a little. Of course you are correct that the original code was broken. The new code is able to initialize the database :smile:

This is my first node.js app. I wrote it to have a bit of fun in minecraft and thought I could turn it into something clever. It's totally incomplete. I wanted to use postgres to store the blocks as I thought that might make various forms of planning easier. Then I got distracted.

This is only really here because I was speaking to a co-worker about AI and I said how easy it was to write a bot in minecraft and how that presented some interesting challenges. I pushed this to show them.

Anyway enough rambling by me heh. Since you are here if you could recommend a good intermediate/advanced javascript or node book then I would really appreciate it. Something that told me how to write javascript idiomatically would be awesome. It's probably rude of me to ask you after the help you have already provided, but I figure you might have some good recommendations.

Anyway, this one is for you:
![You rock](https://media.giphy.com/media/vDO1djCs4urEk/giphy.gif)

**Comment by vitaly-t** [comment]
@matthewfranglen you are welcome! And I am a self-learner, Node.js is one area that never read any book about, too busy writing for it all the time :) All I can say, the online sources and tutorials + StackOverflow are sufficient to learn everything about Node.js.

And when you are ready, you can have a look at [pg-promise-demo](https://github.com/vitaly-t/pg-promise-demo) to see what else you can do ;)
